-- MySQL Script generated by MySQL Workbench
-- Thu 30 Jan 2020 04:06:39 PM UTC
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema loja_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema loja_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja_db` DEFAULT CHARACTER SET utf8 ;
USE `loja_db` ;

-- -----------------------------------------------------
-- Table `loja_db`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_db`.`Usuario` (
  `usuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NULL,
  `senha` VARCHAR(32) NOT NULL,
  `data_inicio` VARCHAR(11) NULL,
  `cpf` BIGINT(11) NOT NULL,
  PRIMARY KEY (`cpf`));


-- -----------------------------------------------------
-- Table `loja_db`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_db`.`Pedido` (
  `idPedido` INT NOT NULL AUTO_INCREMENT,
  `arquivo` VARCHAR(200) NULL,
  `hora` VARCHAR(45) NULL,
  `data` VARCHAR(45) NULL,
  `recado` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `valor` VARCHAR(45) NULL,
  `cores` VARCHAR(45) NULL,
  `dimensoes` VARCHAR(45) NULL,
  `frenteverso` VARCHAR(45) NULL,
  `quantidade_paginas` VARCHAR(45) NULL,
  `num_copias` VARCHAR(45) NULL,
  PRIMARY KEY (`idPedido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja_db`.`Pedido_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_db`.`Pedido_usuario` (
  `cpf` BIGINT(11) NOT NULL,
  `idPedido` INT NOT NULL,
  PRIMARY KEY (`cpf`, `idPedido`),
  INDEX `fk_Usuario_has_Pedido_Pedido1_idx` (`idPedido` ASC),
  INDEX `fk_Usuario_has_Pedido_Usuario_idx` (`cpf` ASC),
  CONSTRAINT `fk_Usuario_has_Pedido_Usuario`
    FOREIGN KEY (`cpf`)
    REFERENCES `loja_db`.`Usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Pedido_Pedido1`
    FOREIGN KEY (`idPedido`)
    REFERENCES `loja_db`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `loja_db`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `loja_db`.`user_info` (
  `cpf` BIGINT(11) NOT NULL,
  `nome` VARCHAR(32) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `cep` VARCHAR(45) NULL,
  `endereco` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `data_nascimento` VARCHAR(45) NULL,
  `imagem` VARCHAR(45) NULL,
  `levelacess` INT NULL DEFAULT 1,
  `tel` VARCHAR(15) NULL,
  PRIMARY KEY (`cpf`),
  INDEX `fk_user_info_Usuario1_idx` (`cpf` ASC),
  CONSTRAINT `fk_user_info_Usuario1`
    FOREIGN KEY (`cpf`)
    REFERENCES `loja_db`.`Usuario` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
